#!/usr/bin/env bash

GOPATH=''

function buildf {
  go build \
  -o bin/human \
  src/*.go
}

function buildb {
  go build \
  -o bin/backend \
  backend/*.go
}

mkdir -p bin

if ! buildf; then exit 1; fi
if ! buildb; then exit 1; fi

echo BUILD SUCCESS
