#!/usr/bin/env bash

mkdir -p data-19138
mkdir -p data-19139
mkdir -p data-19140

function run {
  bin/backend -p 19138 & p0=$!
  bin/backend -p 19139 & p1=$!
  bin/backend -p 19140 & p2=$!
  wait $p0 $p1 $p2
}

if [ -f bin/backend ]
  then run
  else if ./build; then run; fi
fi
