package smhb

const (
	QUEUE_SIZE       = 128
	IO_TIMEOUT       = 10
	TIMESTAMP_LAYOUT = "20060102150405"
	ADDRESS_LENGTH   = len(TIMESTAMP_LAYOUT) + 1
	HEADER_SIZE      = 64
	TARGET_LENGTH    = HEADER_SIZE - 6 - 1
	HANDLE_LIMIT     = TARGET_LENGTH - ADDRESS_LENGTH
	TITLE_LIMIT      = 20
	CONTENT_LIMIT    = 100
)
